PERSISTENCE_DAYS = 30
LOCATION, DATE, TIME, GAME_FORMAT, ENTRIES_CASH_GAME, ENTRIES_TOURNAMENT, STAKE, REGISTER, OPEN_REGISTRATION = range(9)
MIN_BAN_APPROVERS = 5
TABLE_ID_PREFIX = "T"
BAN_PROPOSAL_ID_PREFIX = "B"
GAME_FORMATS_BUTTONS = ['Cash Game', 'Torneo']
STAKES_BUTTONS = ["2€", "5€", "10€", "20€", "50€"]
REGISTRATION_OPTIONS_BUTTONS = ["Si", "No"]
OPEN_REGISTRATION_BUTTONS = ["Apri le iscrizioni!"]
REGEXES = dict(
    date=r"^([1-9]|0[1-9]|1\d|2\d|3[01])\/([1-9]|0[1-9]|1[0-2])\/(((20)\d{2})|(\d{2}))$",
    time=r"^([0-1]?[0-9]|2[0-3]):[0-5][0-9]$",
    game_formats=r"^(Cash Game|Torneo)$",
    number_of_cash_game_players=r"^[2-9]$",
    number_of_tournament_players=r"^(?:[2-9]|(?:[1-9][0-9])|100)$",
    stakes=r"^(2€|5€|10€|20€|50€)$",
    registration_options=r"^(Si|No)$",
    open_registration=r"^(Apri le iscrizioni!)$"
)
